// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cafae8b7-70c8-473b-a1db-aa47d884b4f1.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZmFlOGI3LTcwYzgtNDczYi1hMWRiLWFhNDdkODg0YjRmMSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUwNzMyNTg4LCJleHAiOjIwNjYzMDg1ODh9.example-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);